name: Deploy to DigitalOcean

on:
  push:
    branches: [ "master" ]  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: ðŸ“¦ Checkout code
      uses: actions/checkout@v3

    - name: ðŸ” Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

    - name: ðŸš€ Deploy over SSH
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} << 'EOF'
        cd /var/deploy
        git pull origin master
        cd cards/frontend
        npm install
        npm run build
        cp -r ./dist/* /var/www/html
        cd /var/deploy/cards
        cp server.js /var/cardsServer
        cp createJWT.js /var/cardsServer
        cp api.js /var/cardsServer
        pm2 restart express-server
        pm2 save
        EOF
